language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
install:
  - npm install -g codecov
script:
  - travis_retry npm run lint
  - travis_retry npm test
  - travis_retry npm run report-coverage
deploy:
  provider: npm
  email: ferco0@live.com
  api_key: $NPM_TOKEN
  on:
    tags: true
