language: node_js
services:
  - docker
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_install:
  - docker pull redis
  - docker run -p 6379:6379 -d --rm redis
before_script:
  - npm install
install:
  - npm install -g codecov
script:
  - travis_retry npm run lint
  - travis_retry npm test
  - travis_retry npm run report-coverage
deploy:
  edge: true
  provider: npm
  email: ferco0@live.com
  api_key: $NPM_TOKEN
  on:
    tags: true
