language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - npm install
script:
  - travis_retry npm test
deploy:
  provider: npm
  email: ferco0@live.com
  api_key: $NPM_TOKEN
  on:
    tags: true
